spring:
  application.name: consul_plan_notify
  datasource:
    url: jdbc:postgresql://localhost:5432/consul_notif
    username: postgres
    password: postgres
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: testfist24@gmail.com
    password: xyoj cvkf evum nhmy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  file:
    name: logs/app.log
  level:
    org.springframework.web: DEBUG
    ru.promo.consul_plan_notify: DEBUG
server:
  port: 8181