spring:
  application.name: consul_plan_notify
  datasource:
    url: jdbc:postgresql://localhost:5432/consul_plan
    username: postgres
    password: postgres

  cloud:
    config:
      enabled: false

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: testfist24@gmail.com
    password: xyoj cvkf evum nhmy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
reminder:
  scheduler:
    enabled: true
    cron: "0 0 12 * * ?"
logging:
  file:
    name: logs/app.log
  level:
    org.springframework.web: DEBUG
    ru.promo.consul_plan_notify: DEBUG
server:
  port: 8081